openapi: 3.0.1
info:
  title: Simple Drive API
  description: |
    Simple Drive is a REST API for storing and retrieving binary data (blobs) with multiple storage backend options including File System, Database, Amazon S3, and FTP.
    
    ## Authentication
    All API endpoints require JWT Bearer token authentication except for the health endpoint and token generation.
    
    Example: `Authorization: Bearer eyJhbGciOiJIUzI1NiJ9...`
    
    A token can be obtained via the `/api/v1/tokens` endpoint.
  version: v1
  contact:
    name: Abdulsalam
servers:
  - url: http://localhost:3000
    description: Local development server
paths:
  /health:
    get:
      summary: Health check endpoint
      description: Returns the current status of the API and server timestamp
      tags:
        - Health
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  timestamp:
                    type: string
                    format: date-time
                    example: '2025-05-05T21:24:29.480Z'
  /api/v1/tokens:
    post:
      summary: Generate JWT token
      description: Generate a JWT authentication token for API access
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  description: User identifier
                  example: testuser
                password:
                  type: string
                  description: User password
                  example: password
                scope:
                  type: string
                  description: Optional scope for the token
                  example: storage:read
      responses:
        '201':
          description: Token generated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Token generated successfully
                  token:
                    type: string
                    description: JWT token to be used for authentication
                    example: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoidGVzdHVzZXIiLCJzY29wZSI6ImRlZmF1bHQiLCJjbGllbnRfaW5mbyI6Ik1vemlsbGEvNS4wIiwiaWF0IjoxNjE1MjM0MjY3LCJleHAiOjE2MTUzMjA2Njd9.pU8-XU4iNy9ZF4eG6TMUBK84xx2p-X3W
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Invalid credentials
  /api/v1/blobs/{id}:
    get:
      summary: Retrieve a blob
      description: Retrieve a blob with the given ID
      tags:
        - Blobs
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the blob to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Blob retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: my-unique-blob-id
                  data:
                    type: string
                    description: Base64-encoded content of the blob
                    example: SGVsbG8sIHRoaXMgaXMgYSB0ZXN0IGZpbGUgZm9yIFNpbXBsZSBEcml2ZSE=
                  size:
                    type: integer
                    description: Size of the blob in bytes
                    example: 1024
                  created_at:
                    type: string
                    format: date-time
                    example: '2025-05-06T00:00:00.000Z'
        '404':
          description: Blob not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Blob not found
                  error_code:
                    type: string
                    example: storage.not_found
  /api/v1/blobs:
    post:
      summary: Store a blob
      description: Store a blob with the given ID and base64-encoded data
      tags:
        - Blobs
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - blob_id
                - data
              properties:
                blob_id:
                  type: string
                  description: Unique identifier for the blob
                  example: my-unique-blob-id
                data:
                  type: string
                  description: Base64-encoded content of the blob
                  example: SGVsbG8sIHRoaXMgaXMgYSB0ZXN0IGZpbGUgZm9yIFNpbXBsZSBEcml2ZSE=
      responses:
        '201':
          description: Blob created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: my-unique-blob-id
                  size:
                    type: integer
                    description: Size of the blob in bytes
                    example: 1024
                  created_at:
                    type: string
                    format: date-time
                    example: '2025-05-06T00:00:00.000Z'
                  storage_provider:
                    type: string
                    example: 's3'
        '422':
          description: Invalid parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Missing required parameters
                  details:
                    type: string
                    example: Both blob_id and data are required
                  created_at:
                    type: string
                    format: date-time
                    example: '2025-05-05T21:24:29.567Z'
                  backend:
                    type: string
                    example: file
        '400':
          description: Bad request - invalid parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: content must be base64 encoded
        '401':
          description: Unauthorized - invalid or missing token
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Authentication required
  /api/v1/blobs/{id}:
    get:
      summary: Retrieve a blob
      description: Retrieve a blob by its ID
      tags:
        - Blobs
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The unique blob ID
          example: my-unique-blob-id
      responses:
        '200':
          description: Blob retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  blob_id:
                    type: string
                    example: my-unique-blob-id
                  size:
                    type: integer
                    example: 1024
                  content:
                    type: string
                    description: Base64-encoded content
                    example: SGVsbG8sIHRoaXMgaXMgYSB0ZXN0IGZpbGUgZm9yIFNpbXBsZSBEcml2ZSE=
                  created_at:
                    type: string
                    format: date-time
                    example: '2025-05-05T21:24:29.567Z'
                  backend:
                    type: string
                    example: file
        '401':
          description: Unauthorized - invalid or missing token
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Authentication required
        '404':
          description: Blob not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Blob not found
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
